name: Build and Deploy

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare tag
        id: prep
        run: echo ::set-output name=tag::$(echo $(date +%Y%m%d%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7))
      
      - name: Build the Backend Docker image
        run: |
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/sushi-backend:${{ steps.prep.outputs.tag }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/sushi-backend:latest --file backend/Dockerfile .
      - name: Build the Frontend Docker image
        run: |
          docker build --build-arg REACT_APP_API_URL=https://sushi-backend2.azurewebsites.net/api --tag ${{ secrets.DOCKERHUB_USERNAME }}/sushi-frontend:${{ steps.prep.outputs.tag }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/sushi-frontend:latest --file frontend/Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Backend to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sushi-backend:${{ steps.prep.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sushi-backend:latest
          
      - name: Push Frontend to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sushi-frontend:${{ steps.prep.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sushi-frontend:latest
      
      - name: Trigger Backend Azure Webhook
        run: curl -X POST ${{ secrets.AZURE_WEBHOOK_BACKEND_URL }}

      - name: Trigger Frontend Azure Webhook
        run: curl -X POST ${{ secrets.AZURE_WEBHOOK_FRONTEND_URL }}
